default_settings: null
behaviors:
  iOvcarML:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 8192
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 5
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.4
        encoding_size: 128
        learning_rate: 0.0003
      gail:
        gamma: 0.9
        strength: 0.3
        encoding_size: 64
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: C:\Users\HP\Desktop\MagistrskoDelo2020\iOvcar_Izidor\iOvcar_Izidor\Assets\Demonstrations\Ginelli.demo
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 2000000
    time_horizon: 200
    summary_freq: 20000
    threaded: true
    self_play: null
    behavioral_cloning:
      demo_path: C:\Users\HP\Desktop\MagistrskoDelo2020\iOvcar_Izidor\iOvcar_Izidor\Assets\Demonstrations\Ginelli.demo
      steps: 0
      strength: 1.0
      samples_per_update: 0
      num_epoch: null
      batch_size: null
    framework: pytorch
env_settings:
  env_path: iOvcar/iOvcar_Izidor
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: iOvcarML_adaptGinelliDemo
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
