behaviors:
  iOvcarML:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 8192
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      hidden_units: 512
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.01
        encoding_size: 128
        learning_rate: 0.0003
      gail:
        gamma: 0.9
        strength: 0.02
        encoding_size: 64
        learning_rate: 0.0003
        demo_path: C:\Users\HP\Desktop\MagistrskoDelo2020\iOvcar_Izidor\iOvcar_Izidor\Assets\Demonstrations\Ginelli100.demo
    behavioral_cloning:
      demo_path: C:\Users\HP\Desktop\MagistrskoDelo2020\iOvcar_Izidor\iOvcar_Izidor\Assets\Demonstrations\Ginelli100.demo
    framework: pytorch
    keep_checkpoints: 5
    max_steps: 1e6
    time_horizon: 200
    summary_freq: 20000
    threaded: true
